"""add_tourney_player_table

Revision ID: 056c24383cde
Revises: fefd35fe6e72
Create Date: 2022-09-02 12:45:12.941658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '056c24383cde'
down_revision = 'fefd35fe6e72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_tourney_pair',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tourney_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], name='tourney_player_pair_player_id_constraint'),
    sa.ForeignKeyConstraint(['tourney_id'], ['tourneys.tourneyId'], name='tourney_player_pair_tourney_id_constraint'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('player_tourney_pair', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_player_tourney_pair_player_id'), ['player_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_player_tourney_pair_tourney_id'), ['tourney_id'], unique=False)

    op.execute("create temporary table t1 as select tourneyId as tourney_id, leftPlayerId as player_id from bouts")
    op.execute("create temporary table t2 as select tourneyId as tourney_id, rightPlayerId as player_id from bouts")
    op.execute("create temporary table t3 as select * from t1 union select * from t2")
    op.execute("INSERT into 'player_tourney_pair' (tourney_id, player_id) "
               "select distinct tourney_id, player_id from t3")
    op.execute("drop table t3")
    op.execute("drop table t2")
    op.execute("drop table t1")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player_tourney_pair', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_player_tourney_pair_tourney_id'))
        batch_op.drop_index(batch_op.f('ix_player_tourney_pair_player_id'))

    op.drop_table('player_tourney_pair')
    # ### end Alembic commands ###
