"""add tourney owner

Revision ID: 1af2af3f3f22
Revises: 7eea5279f281
Create Date: 2022-08-16 20:58:46.330318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1af2af3f3f22'
down_revision = '7eea5279f281'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tourneys', schema=None) as batch_op:
        batch_op.create_foreign_key('tourney_owner_id_constraint', 'user', ['owner'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('remember_me',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('remember_me',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    with op.batch_alter_table('tourneys', schema=None) as batch_op:
        batch_op.drop_constraint('tourney_owner_id_constraint', type_='foreignkey')

    # ### end Alembic commands ###
