"""add_group_table

Revision ID: 6fc3fa8b9d7f
Revises: 1af2af3f3f22
Create Date: 2022-08-17 14:35:45.513667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fc3fa8b9d7f'
down_revision = '1af2af3f3f22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('group', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_group_name'), ['name'], unique=True)
    op.execute("INSERT into 'group' (name) VALUES ('everyone')")
    op.execute("INSERT into 'group' (name) select distinct username from user")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_group_name'))

    op.drop_table('group')
    # ### end Alembic commands ###
