"""empty message

Revision ID: 7eea5279f281
Revises: 
Create Date: 2022-07-27 18:58:47.191192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7eea5279f281'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('remember_me', sa.Boolean(), nullable=True))
    op.execute("UPDATE user SET remember_me = 0")
    op.alter_column("user", sa.Column('remember_me', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'remember_me')
    # ### end Alembic commands ###
