"""add_tourney_group

Revision ID: b0cd5dcbcc87
Revises: 62f460f5d2b7
Create Date: 2022-08-22 16:37:26.790754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0cd5dcbcc87'
down_revision = '62f460f5d2b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tourneys', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('tourney_group_id_constraint', 'group', ['group'], ['id'])
    op.execute("UPDATE tourneys SET owner = 1 where owner IS NULL")
    op.execute("create temporary table t1 as select id, name from 'group'")
    op.execute("create temporary table t2 as select distinct user.id, t1.id "
               "as group_id from user, t1 where user.username = t1.name")
    op.execute("update tourneys set 'group' = t2.group_id from t2 where tourneys.owner = t2.id")
    op.execute("drop table t2")
    op.execute("drop table t1")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tourneys', schema=None) as batch_op:
        batch_op.drop_constraint('tourney_group_id_constraint', type_='foreignkey')
        batch_op.drop_column('group')

    # ### end Alembic commands ###
