"""empty message

Revision ID: c84d60b69801
Revises: 
Create Date: 2022-07-21 22:20:16.175295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c84d60b69801'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('uisessions')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('uisessions',
    sa.Column('sessionId', sa.VARCHAR(length=36), nullable=False),
    sa.Column('sessionDict', sa.BLOB(), nullable=True),
    sa.PrimaryKeyConstraint('sessionId')
    )
    # ### end Alembic commands ###
